### ISSUE TITLE
str.charCodeAt is not a function

### ISSUE THREAD

**Issue by James-HHH** [RobLoach/xor-crypt#4]
It says that at node_modules/xor-crypt/xor-crypt.js:42
```
output += String.fromCharCode(key ^ str.charCodeAt(i))
                                        ^

TypeError: str.charCodeAt is not a function
    at xorCrypt (<project folder>\node_modules\[4mxor-crypt[24m\xor-crypt.js:42:47)
    at <project folder>\index.js:8:27
[90m    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3)[39m
```
_`<project folder>` is a replacement name, not the actual directory_

**Comment by RobLoach** [comment]
WAT? https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charCodeAt

Maybe `str` is undefined? Or not a string?
